# Generated by Django 3.2.12 on 2024-07-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20240707_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sic_code',
            field=models.IntegerField(),
        ),
    ]
